services:
  lb:
    image: haproxy:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    cpus: '0.2'
    mem_limit: 30M
    depends_on:
      - api1
      - api2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - fraud_network

  api1:
    build: .
    environment:
      - SOCKET_PATH=/sockets/api1.sock
    volumes:
      - sockets:/sockets
    cpus: '0.4'
    mem_limit: 160M
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - fraud_network

  api2:
    build: .
    environment:
      - SOCKET_PATH=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    cpus: '0.4'
    mem_limit: 160M
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - fraud_network

networks:
  fraud_network:
    driver: bridge

volumes:
  sockets:
