FROM rust:1.75-slim as builder

WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev

COPY load_balancer/ ./

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates

COPY --from=builder /app/target/release/lb-uring /usr/local/bin/lb-uring

CMD ["lb-uring"]