services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    cpus: '0.2'
    cpuset: "0"
    mem_limit: 30M
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - fraud_network
    depends_on:
      - api1
      - api2

  api1:
    build: .
    environment:
      - SOCKET_PATH=/sockets/api1.sock
    volumes:
      - sockets:/sockets
    cpus: '0.4'
    cpuset: "1"
    mem_limit: 160M
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - fraud_network
    security_opt:
      - seccomp:unconfined

  api2:
    build: .
    environment:
      - SOCKET_PATH=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    cpus: '0.4'
    cpuset: "1"
    mem_limit: 160M
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - fraud_network

networks:
  fraud_network:
    driver: bridge

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=50m,mode=1777"