CXX = g++
CXXFLAGS = -std=c++17 -Wall -O3 -mavx2 -fopenmp -ffast-math -pthread \
    -Iinclude \
    -Iinclude/uWebSockets

LDFLAGS = -Llib -fopenmp -luSockets -lssl -lcrypto -lz -lpthread

SRCS = src/ivf.cpp \
       src/utils.cpp \
       src/vector_search.cpp \
       src/main.cpp \
       include/simdjson.cpp

build:
	$(CXX) $(CXXFLAGS) $(SRCS) -o main $(LDFLAGS)

clean:
	rm -f main *.o src/*.o